FROM pytorch/pytorch:1.9.0-cuda11.1-cudnn8-runtime 
# pytorchlightning/pytorch_lightning:base-cuda-py3.8-torch1.9
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir lightning-flash[text] sklearn fire datasets==1.12.1 emoji
